### ISSUE TITLE
How to configure docker containers in label studio and ml backend

### ISSUE THREAD

**Issue by themantalope** [heartexlabs/label-studio-ml-backend#135]
Hi Everyone,

I can't figure out how to properly configure the volumes in the label studio image and the ml-backend image. I keep getting a "file not found" error when trying to submit a labeled image for training/prediction. My `docker-compose.yml` is below:

```yaml
version: "3.8"

services:
  redis:
    image: redis:alpine
    container_name: redis
    hostname: redis
    volumes:
      - "./data/redis:/data"
    expose:
      - 6379
  labeling:
    container_name: labeling_container
    image: heartexlabs/label-studio:latest
    ports: 
      - 8080:8080
    depends_on:
      - modeling
    volumes: 
      - ./data:/data
    environment:
      - LABEL_STUDIO_LOCAL_FILES_SERVING_ENABLED=true
      - LABEL_STUDIO_LOCAL_FILES_DOCUMENT_ROOT=/label-studio/data
    command: > 
      bash -c "
      label-studio start 
      --data-dir /data 
      --log-level DEBUG
      --sampling prediction-score-min 
      --ml-backends http://modeling_container:9090 
    restart: always
  modeling:
    container_name: modeling_container
    build: 
      context: ./modeling
    command: >
      bash -c "
      label-studio-ml init modeling_backend 
      --script tools/${MODEL:-model.py}
      --force true
      &&
      label-studio-ml start ./modeling_backend 
      --port 9090"
    restart: always
    volumes: 
      - ./data:/data
    environment:
      - MODEL_DIR=/data/models
      - RQ_QUEUE_NAME=default
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - USE_REDIS=true
    ports:
      - 9090:9090
    depends_on:
      - redis
    links:
      - redis
```

When I try to submit a labeled image, the `modeling_container` throws this error:

```python
Traceback (most recent call last):
modeling_container |   File "/usr/local/lib/python3.8/urllib/request.py", line 1511, in open_local_file
modeling_container |     stats = os.stat(localfile)
modeling_container | FileNotFoundError: [Errno 2] No such file or directory: '/data/upload/1/26ac1a96-example_1_ocr_scan.jpg'
modeling_container | 
modeling_container | During handling of the above exception, another exception occurred:
modeling_container | 
modeling_container | Traceback (most recent call last):
modeling_container |   File "/usr/local/lib/python3.8/site-packages/label_studio_ml/exceptions.py", line 39, in exception_f
modeling_container |     return f(*args, **kwargs)
modeling_container |   File "/usr/local/lib/python3.8/site-packages/label_studio_ml/api.py", line 32, in _predict
modeling_container |     predictions, model = _manager.predict(tasks, project, label_config, force_reload, try_fetch, **params)
modeling_container |   File "/usr/local/lib/python3.8/site-packages/label_studio_ml/model.py", line 582, in predict
modeling_container |     predictions = m.model.predict(tasks, **kwargs)
modeling_container |   File "/annotation_service_modeling/modeling_backend/model.py", line 117, in predict
modeling_container |     images = [load_image_from_url(url) for url in image_urls]
modeling_container |   File "/annotation_service_modeling/modeling_backend/model.py", line 117, in <listcomp>
modeling_container |     images = [load_image_from_url(url) for url in image_urls]
modeling_container |   File "/annotation_service_modeling/modeling_backend/model.py", line 42, in load_image_from_url
modeling_container |     return io.imread(url)
modeling_container |   File "/usr/local/lib/python3.8/site-packages/skimage/io/_io.py", line 52, in imread
modeling_container |     with file_or_url_context(fname) as fname:
modeling_container |   File "/usr/local/lib/python3.8/contextlib.py", line 113, in __enter__
modeling_container |     return next(self.gen)
modeling_container |   File "/usr/local/lib/python3.8/site-packages/skimage/io/util.py", line 28, in file_or_url_context
modeling_container |     u = urllib.request.urlopen(resource_name)
modeling_container |   File "/usr/local/lib/python3.8/urllib/request.py", line 222, in urlopen
modeling_container |     return opener.open(url, data, timeout)
modeling_container |   File "/usr/local/lib/python3.8/urllib/request.py", line 525, in open
modeling_container |     response = self._open(req, data)
modeling_container |   File "/usr/local/lib/python3.8/urllib/request.py", line 542, in _open
modeling_container |     result = self._call_chain(self.handle_open, protocol, protocol +
modeling_container |   File "/usr/local/lib/python3.8/urllib/request.py", line 502, in _call_chain
modeling_container |     result = func(*args)
modeling_container |   File "/usr/local/lib/python3.8/urllib/request.py", line 1489, in file_open
modeling_container |     return self.open_local_file(req)
modeling_container |   File "/usr/local/lib/python3.8/urllib/request.py", line 1528, in open_local_file
modeling_container |     raise URLError(exp)
modeling_container | urllib.error.URLError: <urlopen error [Errno 2] No such file or directory: '/data/upload/1/26ac1a96-example_1_ocr_scan.jpg'>
modeling_container | 
modeling_container | [2022-06-28 02:59:04,039] [INFO] [werkzeug::_log::225] 172.18.0.4 - - [28/Jun/2022 02:59:04] "POST /predict HTTP/1.1" 500 -

```

I've done my best to follow the tutorials in the label studio documentation and the examples here, but it's not clear to me why I'm getting this error. Any help is much appreciated.
