### ISSUE TITLE
When trying to use the model with an image in my label studio have this error in the logs

### ISSUE THREAD

**Issue by juancalric** [heartexlabs/label-studio-ml-backend#294]
```
File "/usr/local/lib/python3.8/site-packages/label_studio_ml/model.py", line 617, in predict
server         |     predictions = cls._current_model.model.predict(tasks, **kwargs)
server         |   File "/app/segment_anything_model.py", line 69, in predict
server         |     height = kwargs['context']['result'][0]['original_height']
server         | TypeError: 'NoneType' object is not subscriptable
```
my docker-compose

```
version: '3'

x-vision-common:
  &vision-common
  logging:
    options:
      max-size: "100m"
      max-file: "5"
    driver: json-file

services:
  postgres:
    <<: *vision-common
    image: postgres:13.4-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./volumes/postgres-data:/var/lib/postgresql/data
  #----------------------------------------------------------------------------
  #                                label Studio
  #----------------------------------------------------------------------------
  labelstudio:
    <<: *vision-common
    image: heartexlabs/label-studio:1.8.0
    container_name: labelstudio
    depends_on:
      - postgres
    environment:
      DJANGO_DB: default
      POSTGRE_NAME: ${POSTGRES_DB}
      POSTGRE_USER: ${POSTGRES_USER}
      POSTGRE_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRE_PORT: 5432
      POSTGRE_HOST: postgres
      LABEL_STUDIO_DISABLE_SIGNUP_WITHOUT_LINK: "false"
      LABEL_STUDIO_PORT: 80
    ports:
      - 8080:80
  #----------------------------------------------------------------------------
  #                                prefect
  #----------------------------------------------------------------------------
  redis:
    image: redis:alpine
    container_name: redis
    hostname: redis
    volumes:
      - "./volumes/redis:/data"
    expose:
      - 6379
  sam:
    container_name: server
    build: ./docker/segment_anything_model/
    environment:
      - MODEL_DIR=/data/models
      - RQ_QUEUE_NAME=default
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - LABEL_STUDIO_USE_REDIS=true
    ports:
      - 9090:9090
    depends_on:
      - redis
    links:
      - redis
    volumes:
      - "./volumes/sam/data/server:/data"
      - "./volumes/sam/logs:/tmp"
```
